
uninteresting_venue_categories = [
    'Art Gallery',
    'Bath House',
    'Beach',
    'Boat or Ferry',
    'Building',
    'Church',
    'City',
    'College Residence Hall',
    'Conference Room',
    'Country',
    'Field',
    'Flea Market',
    'Grocery Store',
    'Harbor / Marina',
    'Hostel',
    'Hotel',
    'Lawyer',
    'Neighborhood',
    'Office',
    'Park',
    'Plaza',
    'Road',
    'Scenic Lookout',
    'Shopping Mall',
    'Train Station',
    'Train'
]
