
uninteresting_venue_categories = [
    'Art Gallery',
    'Auditorium',
    'Basketball Court',
    'Bath House',
    'Beach',
    'Boat or Ferry',
    'Building',
    'Bus Line',
    'Church',
    'City',
    'College Residence Hall',
    'Conference Room',
    'Convention Center',
    'Country',
    'Coworking Space',
    'Field',
    'Flea Market',
    'Fraternity House',
    'Grocery Store',
    'Gym',
    'Gym / Fitness Center',
    'Gym Pool',
    'Harbor / Marina',
    'Hostel',
    'Hot Spring',
    'Hotel',
    'Island',
    'Lawyer',
    'Medical Center',
    'Mini Golf',
    'Monument / Landmark',
    'Moving Target',
    'Music Festival',
    'Nail Salon',
    'Neighborhood',
    'Office',
    'Park',
    'Parking',
    'Playground',
    'Plaza',
    'Road',
    'Scenic Lookout',
    'Soccer Field',
    'Sorority House',
    'Spa',
    'Theme Park Ride / Attraction',
    'Train Station',
    'Train',
    'Tram Station',
    'University'
]

"""
The following categories are problematic:
- 'Shopping Mall' Several gastropubs are located in or near malls, e.g. Gastropub Stone's
- 'Boat or Ferry' Some bars are stationary boats docked at a pier, e.g. Little Joe
"""
